### ISSUE TITLE
Remove node_modules directory

### ISSUE THREAD

**Issue by bobbyshaw** [meanbee/meanbee-corner-checkout#1]
When the build tools was included and the node modules were installed, it pulled in lots of development dependencies. 

We don't want these committed to the repo, particularly as they result in 288MB of files:

➜  default git:(master) du -hsx *
8.0K    README.md
4.0K    bower.json
 40K    css
164K    docs
  0B    fonts
8.0K    gulpfile.js
 20K    images
8.0K    js
262M    node_modules
4.0K    package.json
4.0K    scsslint.yml
564K    src

Please remove these files and add "node_modules/" to the gitignore.

**Comment by punkstar** [comment]
Ah it looks like the `.gitignore` (along with the other dot files) from https://github.com/meanbee/magento-boilerplate-fe-build-tools was missed when it was copied across.

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
